
# ==== PROGRAM NAME ==== #

NAME = libft.a

# ==== CREATE STATIC ARCHIVE ==== #

AR = ar rcs

# ==== FLAGS AND COMPILER ==== #

CC = cc
CFLAGS = -Wall -Wextra -Werror

# ==== FILES ==== #

SRC = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c \
       ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c \
       ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c \
       ft_calloc.c ft_strdup.c ft_toupper.c ft_tolower.c \
       ft_strchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c \
       ft_strnstr.c ft_atoi.c ft_strrchr.c ft_substr.c \
       ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c \
       ft_strmapi.c ft_striteri.c ft_putchar_fd.c \
       ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
	   ft_putchar.c ft_putnbr.c ft_putstr.c ft_strcmp.c

SRC_BONUS = ft_lstnew_bonus.c ft_lstadd_front_bonus.c \
	ft_lstsize_bonus.c ft_lstlast_bonus.c \
	ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
	ft_lstclear_bonus.c ft_lstiter_bonus.c \
	ft_lstmap_bonus.c

OBJ_DIR = obj
OBJ = $(addprefix $(OBJ_DIR)/, $(SRC:.c=.o))
OBJ_BONUS = $(addprefix $(OBJ_DIR)/, $(SRC_BONUS:.c=.o))

# ==== RULES ==== #

all: $(OBJ_DIR) $(NAME)

$(OBJ_DIR):
	@mkdir -p $(OBJ_DIR)

$(NAME): $(OBJ)
	@$(AR) $(NAME) $(OBJ)

$(OBJ_DIR)/%.o: %.c
	@echo "🔧 Compilation de $<"
	@$(CC) $(CFLAGS) -c $< -o $@

bonus: all $(OBJ_BONUS)
	@echo "➕ Ajout des bonus à $(NAME)..."
	@$(AR) $(NAME) $(OBJ_BONUS)

clean:
	@rm -rf $(OBJ_DIR)

fclean: clean
	@rm -f $(NAME) 

re: fclean all

.PHONY : all bonus clean fclean re
